#!/usr/bin/env python3
"""
NMA Output Validation Script
==============================

Validates completeness and consistency of Network Meta-Analysis outputs.

Checks:
1. Network graph exists and includes all treatments
2. League table has all pairwise comparisons
3. SUCRA rankings match forest plot treatments
4. Inconsistency assessment performed (node-splitting)
5. CINeMA assessment for indirect comparisons
6. Bayesian convergence diagnostics (if gemtc used)
7. Sensitivity analysis (frequentist concordance)

Usage:
    uv run validate_nma_outputs.py --root projects/ici-nsclc
    uv run validate_nma_outputs.py --root projects/ici-nsclc --out 09_qa/nma_validation.md
    uv run validate_nma_outputs.py --root projects/ici-nsclc --strict

Author: AI-assisted meta-analysis pipeline
"""

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple


def extract_treatments_from_extraction(extraction_csv: Path) -> Set[str]:
    """Extract unique treatment names from extraction.csv."""
    treatments = set()

    with open(extraction_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Check common column names for treatment arms
            for col in ["intervention", "treatment", "arm1", "arm2", "treatment_arm"]:
                if col in row and row[col]:
                    treatments.add(row[col].strip())

    return treatments


def check_network_graph(
    project_root: Path, expected_treatments: Set[str]
) -> Tuple[bool, List[str]]:
    """Check if network graph exists and includes all treatments."""
    issues = []

    # Check for network graph file
    graph_paths = [
        project_root / "06_analysis" / "figures" / "network_graph.png",
        project_root / "06_analysis" / "figures" / "figure_network.png",
        project_root / "06_analysis" / "figures" / "nma_network.png",
    ]

    graph_exists = any(p.exists() for p in graph_paths)

    if not graph_exists:
        issues.append(
            "❌ Network graph not found - should be generated by nma_03_network_graph.R"
        )
        return False, issues

    # Check R script for treatment completeness
    r_script = project_root / "06_analysis" / "nma_03_network_graph.R"
    if r_script.exists():
        content = r_script.read_text()

        # Look for network plot creation
        if "netgraph" not in content and "network.plot" not in content:
            issues.append("⚠️ R script missing network plot command")

        # Check if all treatments mentioned
        missing_treatments = []
        for treatment in expected_treatments:
            if treatment not in content:
                missing_treatments.append(treatment)

        if missing_treatments:
            issues.append(
                f"⚠️ Treatments not found in R script: {', '.join(missing_treatments[:3])}"
            )

    return True, issues


def check_league_table(
    project_root: Path, expected_treatments: Set[str]
) -> Tuple[bool, List[str]]:
    """Check if league table has all pairwise comparisons."""
    issues = []

    # Expected number of pairwise comparisons: n*(n-1)/2
    n = len(expected_treatments)
    expected_comparisons = n * (n - 1) // 2

    # Check for league table files
    table_paths = [
        project_root / "06_analysis" / "tables" / "league_table.csv",
        project_root / "06_analysis" / "tables" / "league_table.png",
        project_root / "06_analysis" / "tables" / "table_league.png",
    ]

    table_exists = any(p.exists() for p in table_paths)

    if not table_exists:
        issues.append(
            f"❌ League table not found - should have {expected_comparisons} comparisons"
        )
        return False, issues

    # If CSV exists, validate completeness
    csv_path = project_root / "06_analysis" / "tables" / "league_table.csv"
    if csv_path.exists():
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            rows = list(reader)

        # League table should be symmetric matrix (n x n)
        if len(rows) < n:
            issues.append(f"⚠️ League table has {len(rows)} rows, expected {n}")

    # Check for league table heatmap
    heatmap_path = (
        project_root / "06_analysis" / "tables" / "league_table_heatmap.png"
    )
    if not heatmap_path.exists():
        issues.append(
            "⚠️ League table heatmap not found - run nma_10_tables.R to generate"
        )

    return True, issues


def check_sucra_rankings(
    project_root: Path, expected_treatments: Set[str]
) -> Tuple[bool, List[str]]:
    """Check SUCRA rankings completeness."""
    issues = []

    # Check for SUCRA table/figure
    sucra_paths = [
        project_root / "06_analysis" / "tables" / "sucra_rankings.csv",
        project_root / "06_analysis" / "tables" / "table_rankings.csv",
        project_root / "06_analysis" / "figures" / "rankograms.png",
    ]

    sucra_exists = any(p.exists() for p in sucra_paths)

    if not sucra_exists:
        issues.append(
            "❌ SUCRA rankings not found - should be generated by nma_07_ranking.R"
        )
        return False, issues

    # If CSV exists, validate all treatments present
    csv_path = project_root / "06_analysis" / "tables" / "sucra_rankings.csv"
    if csv_path.exists():
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            rows = list(reader)

        found_treatments = set()
        for row in rows:
            if "treatment" in row:
                found_treatments.add(row["treatment"])

        missing = expected_treatments - found_treatments
        if missing:
            issues.append(f"⚠️ Missing SUCRA for treatments: {', '.join(missing)}")

        # Check for uncertainty intervals
        has_uncertainty = any(
            "lower" in row or "upper" in row or "ci" in row for row in rows
        )
        if not has_uncertainty:
            issues.append("⚠️ SUCRA rankings missing uncertainty intervals")

    return True, issues


def check_inconsistency_assessment(project_root: Path) -> Tuple[bool, List[str]]:
    """Check if inconsistency assessment was performed."""
    issues = []

    # Check R script
    r_script = project_root / "06_analysis" / "nma_05_inconsistency.R"

    if not r_script.exists():
        issues.append(
            "❌ Inconsistency assessment script not found (nma_05_inconsistency.R)"
        )
        return False, issues

    content = r_script.read_text()

    # Check for node-splitting analysis
    if "nodesplit" not in content.lower() and "node.split" not in content.lower():
        issues.append("⚠️ Node-splitting analysis not found in script")

    # Check for design-by-treatment interaction
    if "netsplit" not in content.lower() and "design.effect" not in content.lower():
        issues.append("⚠️ Design-by-treatment interaction test not found")

    # Check for output files
    inconsistency_outputs = [
        project_root / "06_analysis" / "figures" / "nodesplit.png",
        project_root / "06_analysis" / "figures" / "inconsistency_plot.png",
        project_root / "06_analysis" / "figures" / "heat_plot.png",
    ]

    if not any(p.exists() for p in inconsistency_outputs):
        issues.append("⚠️ No inconsistency assessment outputs found")

    return True, issues


def check_cinema_assessment(project_root: Path) -> Tuple[bool, List[str]]:
    """Check CINeMA GRADE assessment for NMA."""
    issues = []

    # Check for CINeMA results
    cinema_paths = [
        project_root / "08_reviews" / "cinema_assessment.csv",
        project_root / "08_reviews" / "grade_nma.csv",
        project_root / "07_manuscript" / "supplementary" / "table_s10_cinema.csv",
    ]

    cinema_exists = any(p.exists() for p in cinema_paths)

    if not cinema_exists:
        issues.append("❌ CINeMA assessment not found - required for NMA publication")
        issues.append(
            "   → Use https://cinema.ispm.unibe.ch/ to assess indirect comparisons"
        )
        return False, issues

    # If exists, check for intransitivity and incoherence assessments
    for path in cinema_paths:
        if path.exists():
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()

            if "intransitivity" not in content.lower():
                issues.append("⚠️ CINeMA missing intransitivity assessment")

            if "incoherence" not in content.lower():
                issues.append("⚠️ CINeMA missing incoherence assessment")

            break

    return True, issues


def check_bayesian_convergence(project_root: Path) -> Tuple[bool, List[str]]:
    """Check Bayesian model convergence diagnostics."""
    issues = []

    # Check R script for convergence checks
    r_script = project_root / "06_analysis" / "nma_04_models.R"

    if not r_script.exists():
        issues.append("⚠️ NMA models script not found")
        return False, issues

    content = r_script.read_text()

    # Check for convergence diagnostics
    convergence_checks = [
        ("gelman.diag", "Gelman-Rubin diagnostic"),
        ("geweke.diag", "Geweke diagnostic"),
        ("trace", "Trace plots"),
        ("autocorr", "Autocorrelation plots"),
    ]

    missing_checks = []
    for check_pattern, check_name in convergence_checks:
        if check_pattern not in content.lower():
            missing_checks.append(check_name)

    if len(missing_checks) >= 3:
        issues.append(
            f"⚠️ Missing convergence diagnostics: {', '.join(missing_checks[:2])}"
        )

    # Check for sufficient iterations
    if "n.iter" in content:
        # Extract iteration count
        match = re.search(r"n\.iter\s*=\s*(\d+)", content)
        if match:
            n_iter = int(match.group(1))
            if n_iter < 10000:
                issues.append(f"⚠️ Low MCMC iterations ({n_iter}) - recommend ≥10,000")

    return True, issues


def check_sensitivity_analysis(project_root: Path) -> Tuple[bool, List[str]]:
    """Check sensitivity analysis (frequentist concordance)."""
    issues = []

    # Check for sensitivity script
    r_script = project_root / "06_analysis" / "nma_09_sensitivity.R"

    if not r_script.exists():
        issues.append("⚠️ Sensitivity analysis script not found (nma_09_sensitivity.R)")
        return False, issues

    content = r_script.read_text()

    # Check for frequentist comparison (netmeta)
    if "netmeta" not in content.lower():
        issues.append(
            "⚠️ Frequentist sensitivity analysis not found (should use netmeta)"
        )

    # Check for leave-one-out analysis
    if "leave" not in content.lower() and "loo" not in content.lower():
        issues.append("⚠️ Leave-one-out sensitivity analysis not found")

    return True, issues


def check_cnma_outputs(project_root: Path) -> Tuple[bool, List[str]]:
    """Check CNMA outputs (optional — only if CNMA was run)."""
    issues = []

    # Check if CNMA was run (indicated by cnma_report.txt)
    cnma_report = project_root / "06_analysis" / "cnma_report.txt"

    if not cnma_report.exists():
        # CNMA is optional — not an issue if not run
        return True, ["ℹ️ CNMA not run (no combination treatments or not applicable)"]

    # If CNMA was run, validate outputs
    # Check component forest plot
    component_plot = (
        project_root / "06_analysis" / "figures" / "cnma_components_additive.png"
    )
    if not component_plot.exists():
        issues.append("⚠️ CNMA component forest plot not found")

    # Check interaction test results
    interaction_csv = (
        project_root / "06_analysis" / "tables" / "cnma_interaction_test.csv"
    )
    if not interaction_csv.exists():
        issues.append(
            "⚠️ CNMA interaction test results not found "
            "(tables/cnma_interaction_test.csv)"
        )

    # Check model comparison table
    model_comparison_csv = (
        project_root / "06_analysis" / "tables" / "cnma_model_comparison.csv"
    )
    if not model_comparison_csv.exists():
        issues.append(
            "⚠️ CNMA model comparison table not found "
            "(tables/cnma_model_comparison.csv)"
        )

    if not issues:
        issues.append("✅ CNMA outputs complete (component effects + interaction test)")

    return True, issues


def check_meta_regression_outputs(project_root: Path) -> Tuple[bool, List[str]]:
    """Check NMA meta-regression outputs (optional)."""
    issues = []

    metareg_report = project_root / "06_analysis" / "nma_metareg_report.txt"

    if not metareg_report.exists():
        return True, ["ℹ️ NMA meta-regression not run (no covariates or not applicable)"]

    # Check regression results
    metareg_csv = (
        project_root / "06_analysis" / "tables" / "nma_metareg_results.csv"
    )
    if not metareg_csv.exists():
        issues.append("⚠️ Meta-regression results CSV not found")

    if not issues:
        issues.append("✅ NMA meta-regression outputs present")

    return True, issues


def check_transitivity_tests(project_root: Path) -> Tuple[bool, List[str]]:
    """Check statistical transitivity assessment outputs (optional)."""
    issues = []

    transit_report = (
        project_root / "06_analysis" / "transitivity_assessment_report.txt"
    )

    if not transit_report.exists():
        return True, [
            "ℹ️ Statistical transitivity tests not run "
            "(ensure clinical assessment in nma-assumptions.md is done)"
        ]

    # Check traffic light table
    transit_csv = project_root / "06_analysis" / "tables" / "transitivity_tests.csv"
    if not transit_csv.exists():
        issues.append("⚠️ Transitivity test results CSV not found")

    if not issues:
        issues.append("✅ Statistical transitivity assessment complete")

    return True, issues


def generate_validation_report(project_root: Path, strict: bool = False) -> Dict:
    """Generate comprehensive NMA validation report."""

    # Extract expected treatments
    extraction_csv = project_root / "05_extraction" / "round-01" / "extraction.csv"

    if not extraction_csv.exists():
        return {"valid": False, "error": f"Extraction data not found: {extraction_csv}"}

    expected_treatments = extract_treatments_from_extraction(extraction_csv)

    if len(expected_treatments) < 3:
        return {
            "valid": False,
            "error": f"Only {len(expected_treatments)} treatments found - NMA requires ≥3",
        }

    # Run all checks
    checks = [
        ("Network graph", check_network_graph, [project_root, expected_treatments]),
        ("League table", check_league_table, [project_root, expected_treatments]),
        ("SUCRA rankings", check_sucra_rankings, [project_root, expected_treatments]),
        ("Inconsistency assessment", check_inconsistency_assessment, [project_root]),
        ("CINeMA GRADE", check_cinema_assessment, [project_root]),
        ("Bayesian convergence", check_bayesian_convergence, [project_root]),
        ("Sensitivity analysis", check_sensitivity_analysis, [project_root]),
        ("CNMA (component NMA)", check_cnma_outputs, [project_root]),
        ("NMA meta-regression", check_meta_regression_outputs, [project_root]),
        ("Transitivity tests", check_transitivity_tests, [project_root]),
    ]

    results = {
        "n_treatments": len(expected_treatments),
        "treatments": sorted(expected_treatments),
        "checks": {},
        "all_issues": [],
        "valid": True,
    }

    for name, check_func, args in checks:
        passed, issues = check_func(*args)
        results["checks"][name] = {"passed": passed, "issues": issues}
        results["all_issues"].extend(issues)

        if not passed and strict:
            results["valid"] = False

    return results


def format_validation_report(results: Dict) -> str:
    """Format validation results as markdown."""

    if "error" in results:
        return f"# NMA Validation Report\n\n❌ **Error**: {results['error']}\n"

    lines = [
        "# NMA Output Validation Report",
        "",
        f"**Treatments**: {results['n_treatments']} ({', '.join(results['treatments'])})",
        f"**Expected Comparisons**: {results['n_treatments'] * (results['n_treatments'] - 1) // 2}",
        "",
        "---",
        "",
        "## Validation Checks",
        "",
    ]

    for check_name, check_data in results["checks"].items():
        status = "✅" if check_data["passed"] else "❌"
        lines.append(f"### {status} {check_name}")

        if check_data["issues"]:
            lines.append("")
            for issue in check_data["issues"]:
                lines.append(f"- {issue}")
        else:
            lines.append("")
            lines.append("✅ All checks passed")

        lines.append("")

    # Summary
    lines.extend(["---", "", "## Summary", ""])

    passed_count = sum(1 for c in results["checks"].values() if c["passed"])
    total_count = len(results["checks"])

    lines.append(f"**Passed**: {passed_count}/{total_count} checks")
    lines.append("")

    if results["valid"]:
        lines.append("✅ **NMA outputs valid for publication**")
    else:
        lines.append("❌ **Critical issues found - address before submission**")

    lines.extend(
        [
            "",
            "---",
            "",
            "## Required NMA Outputs for Publication",
            "",
            "Per PRISMA-NMA checklist:",
            "",
            "- [ ] Network graph (geometry)",
            "- [ ] League table (all pairwise comparisons)",
            "- [ ] Treatment rankings (SUCRA/P-scores with uncertainty)",
            "- [ ] Inconsistency assessment (node-splitting + design-by-treatment)",
            "- [ ] CINeMA GRADE assessment (intransitivity + incoherence)",
            "- [ ] Bayesian convergence diagnostics (if gemtc used)",
            "- [ ] Sensitivity analysis (frequentist concordance)",
            "",
        ]
    )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Validate NMA outputs for publication readiness",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  uv run validate_nma_outputs.py --root projects/ici-nsclc
  uv run validate_nma_outputs.py --root projects/ici-nsclc --out 09_qa/nma_validation.md
  uv run validate_nma_outputs.py --root projects/ici-nsclc --strict
        """,
    )

    parser.add_argument("--root", required=True, help="Project root directory")
    parser.add_argument("--out", help="Output markdown file (default: stdout)")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail validation if any check fails (exit code 1)",
    )

    args = parser.parse_args()

    project_root = Path(args.root)
    if not project_root.exists():
        print(f"Error: Project root not found: {project_root}", file=sys.stderr)
        sys.exit(1)

    # Generate validation report
    results = generate_validation_report(project_root, args.strict)

    # Format report
    report = format_validation_report(results)

    # Output
    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report)
        print(f"✅ NMA validation report written to: {out_path}")
    else:
        print(report)

    # Exit code
    if args.strict and not results.get("valid", False):
        sys.exit(1)


if __name__ == "__main__":
    main()
